name: residencia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  excel: ^4.0.6
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
