name: residencia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  excel: ^4.0.6
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  rename_app: ^1.6.5
  share_plus: ^12.0.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
